# Generated by Django 5.1.2 on 2024-12-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tramite_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definicion',
            name='tipo',
        ),
    ]
